dearmoment-team/dear-moment-frontend

app/components/molecule/Dropbox.tsx
package.json
tailwind.config.ts
yarn.lock

- 드롭박스 컴포넌트 기능 구현
- 스크롤 숨김, 노출 tailiwind Utility 추가
- 컴포넌트 사용시 각 이벤트 발생 시 호출할 이벤트 props 함수 옵션값으로 추가하여 재사용될 때 유연성 고려하여 작성했습니다.
close #10

[DM-006] 드롭박스 컴포넌트 구현

---

app/components/ui/Chip.tsx

- Chip 컴포넌트 기능 구현
- 기타 등등..
close #14

[DM-008] Chip 컴포넌트 구현

---

app/components/Appbar.tsx
package.json
tailwind.config.ts

- Appbar 컴포넌트 UI 구현
- dev 서버 포트 변경(8080)
- container 모바일(sm) 사이즈 수정
- Appbar에 아이콘, 타이틀, 로고 props를 통해 상황에 맞게 사용하면 될 것 같습니다.
close #16

[DM-009] Appbar 컴포넌트 구현

---

app/(home)/page.tsx
app/assets/icons/Icon_User_Filled.tsx
app/components/NavigationBar.tsx

- NavigationBar 컴포넌트 기능 구현
- pathname으로 'Home', 'Like', 'My' 활성화, 비활성화 UI 처리
- 각자 작업하는 페이지의 layout.tsx에 추가해서 작업하면 통일성있어 좋을 것 같습니다.
close #24

[DM-012] NavigationBar 컴포넌트 구현

---

next.config.ts

- next.config 파일 타입 에러 해결
- 기타 등등..

[Hotfix] next config 타입 오류 해결

---

app/components/ui/button.tsx

- Figma 상 버튼 종류가 6개로 파악되어 6종류에 대응할 수 있도록 Button 컴포넌트를 구현하였습니다. (variant 속성, 속성명은 바탕색을 기준으로 부여했습니다.)
- 한 가지 고민되는 부분은, **추후 버튼 종류가 늘어나는 것 대비 및 유연성 증가를 위해 사용하는 곳에서 버튼 스타일을 받는 구조로 컴포넌트를 구현**하는게 좋을까요 ? 아니면 지금 상태처럼 **Button 컴포넌트 내부에서 variant를 사용하는 방법**이 좋을까요?
PS. 오랜만에 코드를 쳐서 감이 많이 죽은 듯 합니다....ㅠㅠ (빨리 취업 안 시켜 준 회사들이 문제에요) 부족한 점이나 수정해야할 부분이 있다면 사소한 부분이라도 리뷰 남겨주시면 감사하겠습니다 !!

[DM-004] Button 컴포넌트 구현

---

app/(home)/_components/Home.tsx
app/(home)/_components/ProductCard.tsx
app/(home)/controllers/FilteringController.ts
app/(home)/controllers/HomeController.ts
app/(home)/controllers/ProductCardController.ts
app/api/config/index.ts
app/api/inquiries/index.ts
app/api/inquiries/types.ts
app/api/likes/index.ts
app/api/likes/types.ts
app/api/products/types.ts
app/api/studio/types.ts
app/api/utils/http.ts
app/components/molecule/Dropbox.tsx
app/globals.css
app/options/[productId]/[optionId]/_components/OptionDetail.tsx
app/options/[productId]/[optionId]/controllers/productOptionController.ts
app/products/[id]/_components/InquiryBottomSheet.tsx
app/products/[id]/_components/ProductDetail.tsx
app/products/[id]/_components/ProductOptionCard.tsx
app/products/[id]/_components/ProductTabs.tsx
app/products/[id]/controllers/productDetailController.ts
app/products/[id]/controllers/productOptionController.ts
app/products/[id]/page.tsx

- 상품 좋아요, 옵션 API 연동
- 상품 옵션 좋아요 변경 시 session 스토리지 상태값 저장하여 productDetail 페이지에서 조건부로 refetch 적용
- 
- 기타 등등..

[DM-019] 상품 및 옵션 좋아요 API 연동

---

app/api/config/index.ts
app/api/inquiry/index.ts
app/api/inquiry/types.ts
app/api/utils/http.ts
app/components/ui/dialog.tsx
app/components/ui/textarea.tsx
app/globals.css
app/my/feedback/page.tsx
app/my/inquiry/page.tsx
app/my/page.tsx
app/my/report-author-error/edit/page.tsx
app/my/report-author-error/page.tsx
tailwind.config.ts

- MY 페이지 UI 구현
- Textarea 컴포넌트 추가
- 서비스 문의, 스튜디오 문의, 상품 옵션 API 연동
- 기타 등등..

[DM-020] 마이페이지 UI 및 API 연동

---

app/(home)/_components/ProductList.tsx
app/api/inquiries/index.ts
app/components/LoadingSpinner.tsx
app/my/feedback/page.tsx
app/options/[productId]/[optionId]/page.tsx
app/products/[id]/page.tsx

- 중첩 페이지 라우팅 타입 수정
- LoadingSpinner 라이브러리 서버 렌더링 오류 처리
- 기타 등등..

Develop > Production - 배포 타입 오류 수정

---

app/api/config/index.ts
app/api/users/index.ts
app/api/users/types.ts
app/api/utils/http.ts
app/onboarding/page.tsx
app/onboarding/step2/page.tsx

- PUT > PATCH 수정
- localStorage > url params 사용하여 nickname 전달
- 사용자 프로필 수정, 조회 API 추가
- 기타 등등..

[DM-024] Users API 연동

---

app/onboarding/step2/Form.tsx
app/onboarding/step2/Info.tsx
app/onboarding/step2/page.tsx

- useSearchParams 에러바운더리 추가
- 기타 등등..

[Deploy] hotfix useSearchParams <Suspense> 에러 바운더리 처리

---

app/(home)/_components/FilteringItems.tsx
app/onboarding/step2/page.tsx

- suspense fallback 추가
- 불필요한 선언 제거
- 기타 등등..

[Deploy] hotfix 불필요한 선언 제거 및 suspense fallback 추가

---

app/(home)/_components/FilteringItems.tsx
app/(home)/layout.tsx
app/(home)/page.tsx

- 필터링 인풋 포커싱 로직 추가
- 메인 페이지 모바일 환경 한 화면에 보이도록 수정
- 기타 등등..

[DM-025] 필터링 인풋 포커싱 로직 추가 및 메인 페이지 모바일 환경 한 화면에 보이도록 수정

---

app/(home)/_components/FilteringItems.tsx
app/onboarding/step2/page.tsx

- 필터링 인풋 포커싱 추가 
- 메인 페이지 모바일 환경 한 화면에 나타나도록 수정
- 기타 등등..

[Deploy] 필터링 인풋 포커싱 추가 및 메인 페이지 모바일 환경 한 화면에 나타나도록 수정

---

app/(home)/_components/FilteringItems.tsx
app/(home)/_components/ProductList.tsx
app/(home)/layout.tsx

- Input 포함하는 부모 요소 높이 auto로 설정
- Home 화면 dvh 동작 대신 window.innerHeight 로 수정
- 기타 등등..

[DM-025] 모바일 키패드 가려짐 해결, 메인 페이지 바텀 가려짐 해결

---

app/(home)/_components/FilteringItems.tsx
app/(home)/_components/ProductList.tsx
app/(home)/layout.tsx
app/(home)/page.tsx

- Input 포함하는 부모 요소 높이 auto로 설정
- Home 화면 dvh 동작 대신 window.innerHeight 로 수정
- 기타 등등..

[Deploy] 키패드 가려짐 이슈, 메인 페이지 바텀 가려짐 이슈 해결

---

app/(home)/_components/FilteringItems.tsx
app/(home)/_components/FilteringModal.tsx
app/(home)/layout.tsx
app/components/ui/input.tsx

- 필터링 모달 가격 카테고리 위치 수정, 홈 화면 높이 동적 js 로직 추가
- 기타 등등..

[DM-025] 필터링 모달 가격 카테고리 위치 수정, 홈 화면 높이 동적 js 로직 추가

---

app/(home)/_components/FilteringItems.tsx
app/(home)/_components/FilteringModal.tsx
app/(home)/_components/ProductList.tsx
app/(home)/layout.tsx
app/components/ui/input.tsx

- 필터링 모달 가격 카테고리 위치 수정, 홈 화면 높이 동적 js 로직 추가
- 기타 등등..

[Deploy] 필터링 모달 가격 카테고리 위치 수정, 홈 화면 높이 동적 js 로직 추가

---

app/like/_components/ProductCard.tsx
app/like/_components/StudioCard.tsx

- 좋아요 해제 시 카드가 선택되어 상세페이지가 열리는 이벤트 버블링 방지(찜한 상품, 스튜디오)
`e.stopPropagation();` 
- 나머지는 prettier 자동 설정되어 수정됨
- 기타 등등..

Feature/dm-027 이벤트 버블링 방지 코드 추가(찜한 상품, 찜한 스튜디오)

---

app/login/callback/success/page-ui.tsx

- 로그인 성공 시 백엔드로부터 받은 토큰 값 쿠키에 저장함(미들웨어에서 사용하기 위한 목적)
- 기타 등등..

feat : 로그인 성공 시 백엔드로부터 받은 토큰 값 쿠키에 저장함(미들웨어에서 사용하기 위한 목적)

---

app/admin/_hooks/product/useProduct.ts

상품 등록 시 발생하는 에러를 수정했습니다.
- optionType이 SINGLE일 땐 partnerShops 배열을 빈 배열로 넣도록 수정했습니다.
- console.log를 제거했습니다.

[DM-029] 상품 등록 시 발생하는 에러 수정

---

app/(home)/_components/FilteringItems.tsx

[Deploy] - hotfix filter order 수정

---

app/api/config/index.ts

- 초기 렌더링 시 서버 컴포넌트에서 에러발생하고있었음.
헤더에 토큰정보가 빠져 권한이 없어 나는 문제로 클라이언트/서버 컴포넌트 구분 없이 토큰정보 주입하여 권한 에러 해결함

fix: 좋아요페이지 403 에러 수정

---

app/my/_services/my.ts
app/my/page.tsx

- 마이페이지 회원명 노출 기능 추가
로컬에서 로그인을 아직 못해서 테스트는 못해본 상태입니다. 로그인 문제 해결되는대로 테스트 진행하겠습니다 :)

마이페이지 회원명 노출

---

app/(home)/_components/ProductCard.tsx
app/auth/LoginConfirmModal.tsx
app/components/ui/Modal.tsx
app/login/callback/success/page-ui.tsx
app/options/[productId]/[optionId]/_components/OptionDetail.tsx
app/products/[id]/_components/ProductDetail.tsx

<LoginConfirmModal.tsx> : 로그인 요청 모달 UI 개발
<ProductCard.tsx>, <ProductDetail.tsx>, <OptionDetail.tsx> : 대상페이지지
<Modal.tsx> : 모달 컴포넌트 버튼 UI 수정(버튼 backgroud, text color 수정)
<page-ui.tsx> : 로그인 성공 시 localStorage에 로그인 성공여부(isLoggedIn) 'true'로 저장(String)
- 기타 등등..

feat: 클라이언트 컴포넌트에서 로그인 하지않고 좋아요 버튼 클릭, 문의하기 클릭 시 로그인 요청 모달 띄워 로그인 유도

---

app/admin/_components/StudioForm.tsx
app/admin/_hooks/studio/useStudio.ts

연락처 입력 시 자동 하이픈 생성

---

app/admin/_components/ImageUploader.tsx
app/admin/_components/ProductForm.tsx
app/admin/_components/ProductPackageOption.tsx
app/admin/_components/ProductSingleOption.tsx
app/admin/_components/RequirdField.tsx
app/admin/_components/StudioForm.tsx

- RequirdField 컴포넌트 구현
- 필수 입력 필드 가시성 증가를 위해 배경색 적용
- Approve 해주시면 제가 머지 하겠습니다 :)

필수 입력 필드 가시성 증가를 위해 배경색 적용

---

app/admin/_components/StudioForm.tsx
app/admin/_hooks/studio/useStudio.ts

- 스튜디오 폼 필드값 (`영업 스튜디오`) 미출력 문제 해결
- Approve 해주시면 제가 머지 하겠습니다 :)

스튜디오 폼 필드값 미출력 문제 해결

---

app/like/_components/LikePage.tsx
app/like/page.tsx
app/my/_services/my.ts
app/my/quit/page.tsx
yarn.lock

1. 회원 탈퇴 step 1~3 상태로 관리
- reason : 탈퇴사유 입력화면
- confirm : 탈퇴 확인 화면
- complete : 탈퇴 완료 화면
2. 좋아요 페이지 바로가기 구현 위해 파라미터 추가(initialTab)

feat : 회원 탈퇴 개발

---

.eslintrc.json
app/like/page.tsx

[Hotfix] build 에러 해결

---

app/layout.tsx

[Hotfix] GA4 빌드 에러 해결

---

app/onboarding/step2/Form.tsx
middleware.ts

[QA] 회원 정보 입력 스킵 기능 추가

---

app/login/callback/success/page-ui.tsx
app/my/page.tsx
app/my/quit/page.tsx

탈퇴하기 기능 일부 누락되어 추가함
- page-ui.tsx : 로그인 여부 localStorage에 저장기능 누락되어 다시 추가함
- /my/page.tsx : 마이페이지 탈퇴하기 메뉴 테스트용으로 임시 추가, 디자이나 반영 시 수정예정
- /my/quit/page.tsx : 탈퇴하기 페이지 내 탈퇴 성공 시 localStorage, cookie 초기화, 취소 버튼 기능 누락되어 추가, 다음(탈퇴하기) 버튼 디자인 미적용 누락되어 추가

탈퇴하기 기능 일부 누락되어 추가함

---

.eslintrc.json
app/layout.tsx
app/like/page.tsx

[Deploy] 회원탈퇴 누락 기능 추가 및 onboarding 스킵 기능 추가

---

app/assets/icons/Icon_Studio.tsx
app/assets/icons/index.ts
app/assets/icons/svg/studio.svg
app/options/[productId]/[optionId]/_components/OptionDetail.tsx
app/products/[id]/_components/ProductDetail.tsx

[Hotfix] 스튜디오, 옵션 상세 기본 이미지 추가

---

app/(home)/controllers/ProductCardController.ts
app/api/utils/http.ts
app/layout.tsx
app/like/_components/StudioCard.tsx
app/products/[id]/controllers/productDetailController.ts

- 좋아요 추가 후 likeId 갱신 로직 추가
- 기타 등등..

fix: 좋아요 추가 후 likeId 이전 업데이트 로직 추가

---

app/(home)/_components/ProductCard.tsx
app/api/products/types.ts
app/like/_components/ProductCard.tsx
app/like/_components/StudioCard.tsx
app/options/[productId]/[optionId]/_components/OptionDetail.tsx
app/products/[id]/_components/ImageViewerModal.tsx
app/products/[id]/_components/ProductDetail.tsx
app/products/[id]/_components/ProductOptionCard.tsx
app/products/[id]/_components/ProductTabs.tsx
next.config.ts

[지라 작업 링크](https://dearmoment.atlassian.net/jira/software/projects/SCRUM/boards/1/timeline?selectedIssue=SCRUM-9)
- 파트너샵 링크 연결
- 할인율 로직 수정
- 이미지 화면 꽉채우기
- 기타 등등..

[Hotfix] 파트너샵 링크 추가, 이미지 화면 꽉채우기, 할인율 로직 수정

---

app/products/[id]/_components/ProductDetail.tsx

[Deploy] 상품 추가 이미지 노출

---

app/login/page.tsx
app/utils/auth.ts

토큰 만료 테스트 목적 배포

---

app/login/page.tsx
app/utils/auth.ts

로그인하지 않은 사용자도 checkTokenExpiration 함수가 실행되어 불필요한 로그인 페이지 리다이렉트 강제 발생하고있어 토큰이 있는 사용자만 유효시간 검사를 하도록 수정함
- 기타 등등..

fix : 로그인하지 않은 사용자는 토큰 체크를 하지않도록 수정

---

app/(home)/hooks/useScroll.ts
app/login/callback/success/page-ui.tsx
app/my/_services/my.ts

- addInfoIsSkip 값 추가하고 분기 조건으로 추가
- 기타 등등..

fix: 로그인 정보 입력 후 스킵 로직 파라미터 수정

---

app/like/_components/LikePage.tsx
app/like/_components/Tab.tsx
app/like/page.tsx

- addInfoIsSkip 값 추가
- 기타 등등..

[Deploy] 로그인 정보 입력 후 스킵 로직 파라미터 수정

---

app/utils/auth.ts

토큰 유효시간 1시간으로 수정. 만료 시 로그인 유도
- 기타 등등..

fix : 토큰 유효시간 1시간으로 수정. 만료 시 로그인 유도

---

app/products/[id]/_components/ImageViewerModal.tsx
app/products/[id]/_components/MainImageViewerModal.tsx
app/products/[id]/_components/ProductDetail.tsx

[DM-039] 이미지 뷰어 무한 캐러셀 구현

---

app/like/_components/LikePage.tsx
app/like/_components/Tab.tsx
app/like/page.tsx
app/utils/auth.ts

[Deploy] 이미지 뷰어 무한 캐러셀 구현 배포

---

app/(home)/_components/ProductCard.tsx
app/(home)/_components/ProductList.tsx
app/(home)/_components/SkeletonCard.tsx
app/components/ui/skeleton.tsx
app/products/[id]/_components/ProductDetail.tsx
next.config.ts
package.json
yarn.lock

- Skeleton UI 추가
- Image priority 추가 및 LCP 이미지 최적화
- 기타 등등..

[DM-040] 메인 상품 skeleton UI 적용, 불필요한 props 제거, LCP 최적화

---

app/(home)/_components/ProductList.tsx

[Deploy] 메인 상품 조회 최대금액 100만원 > 1억원 수정

---

app/products/[id]/_components/ProductDetail.tsx

[Hotfix] 작가 소개 노출

---

app/(home)/_components/ProductList.tsx

[Deploy] 스튜디오 상세 페이지 작가 소개글 노출
